[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "CARGO_TERM_COLOR",
    "RUST_BACKTRACE",
]

[target.x86_64-unknown-linux-musl.env.set]
OPENSSL_STATIC = "1"
OPENSSL_DIR = "/usr/local/musl"
